<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_moje_alza</name>
   <tag></tag>
   <elementGuidId>7c4814ec-4ae8-4802-82d2-e0dd40c81fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.header-alz-25.header-alz-26</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/div[2]/div/div/div/div/header/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;headerContextMenuToggle&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb694970-3783-4e9e-838a-e8342c75fcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-alz-25 header-alz-26</value>
      <webElementGuid>693197ac-ec1f-4dc8-9821-92ed636f32af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>headerContextMenuToggle</value>
      <webElementGuid>ff5d40e8-3545-4e1e-914a-ffa31c6abd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Moje Alza</value>
      <webElementGuid>2fb6140f-0a3f-4b77-82b6-ab4756d8bafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;component header&quot;]/div[@class=&quot;MuiScopedCssBaseline-root header-1ym4w4j&quot;]/div[@class=&quot;header-alz-1&quot;]/div[@class=&quot;header-alz-3&quot;]/header[@class=&quot;header-alz-4&quot;]/div[@class=&quot;header-alz-15&quot;]/div[@class=&quot;header-alz-24&quot;]/button[@class=&quot;header-alz-25 header-alz-26&quot;]</value>
      <webElementGuid>664fd1bc-19ec-431e-b952-6f3a3c6dc7c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[2]/div/div/div/div/header/div/div/button</value>
      <webElementGuid>76a9fed5-0971-4fd4-aafd-ab3e1cdbcaa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hledat'])[1]/preceding::button[2]</value>
      <webElementGuid>419fdc0b-3872-4f2f-9e0d-56acb86e0b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d86f9315-c09c-44eb-9b27-b29625bd835c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Moje Alza' or . = 'Moje Alza')]</value>
      <webElementGuid>8a7e1e68-b3db-4cee-b825-337ae0d46233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
