<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notebooky</name>
   <tag></tag>
   <elementGuidId>ee912361-ef96-4fc0-83a7-6fa3fac30e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ltp']/div[2]/div/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;category-tiles&quot;] >> internal:role=link[name=&quot;Notebooky&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b79b1671-160d-4a20-a04b-84ae0041e452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catalogLocalTitlePage-alz-4</value>
      <webElementGuid>4f742dd1-40d2-4801-b354-497ec6c80e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.alza.cz/notebooky/18842920.htm</value>
      <webElementGuid>dc4b9edd-daa7-4a61-a124-e21cd6dad43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notebooky</value>
      <webElementGuid>cdbe1d41-5da7-47c3-8684-e2e5c7cf1a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ltp&quot;)/div[2]/div[@class=&quot;react-category-tiles component catalogLocalTitlePage&quot;]/div[@class=&quot;MuiScopedCssBaseline-root catalog-local-title-page-1ym4w4j&quot;]/div[@class=&quot;catalogLocalTitlePage-alz-1&quot;]/div[@class=&quot;catalogLocalTitlePage-alz-2&quot;]/a[@class=&quot;catalogLocalTitlePage-alz-4&quot;]</value>
      <webElementGuid>3b412d3d-7c94-4e2f-83a5-379ac63ef637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ltp']/div[2]/div/div/div/div[3]/a</value>
      <webElementGuid>a06d4c2e-65fc-4694-8359-b3c5f0a38ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple novinky'])[1]/following::a[1]</value>
      <webElementGuid>4a8a843d-018e-4f4c-a9d5-53dd489a71e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AlzaPlus+ slevy'])[1]/following::a[2]</value>
      <webElementGuid>65e2a94f-5f94-4829-ab04-bd5dad35d279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Počítače'])[1]/preceding::a[1]</value>
      <webElementGuid>0b5d1799-48ec-46ff-91ef-7bd7961aef55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.alza.cz/notebooky/18842920.htm')]</value>
      <webElementGuid>e96e921a-1f4a-49cf-a25b-31f60980770d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>c7b82c53-b522-40e5-b6d8-a6ba50c4ba7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.alza.cz/notebooky/18842920.htm' and (text() = 'Notebooky' or . = 'Notebooky')]</value>
      <webElementGuid>71ca7d94-8224-4d33-941b-ddfb60b573ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
