<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ulozit_formular_registrace</name>
   <tag></tag>
   <elementGuidId>cef07b1b-6fea-47d9-9e8f-d80b3d750279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btnx.normal.green.arrowedRight.floatRight.order4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orderpage']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Uložit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>adb1d786-2b29-4e02-8c3a-890c1327146c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnx normal green arrowedRight floatRight order4</value>
      <webElementGuid>0017380a-d5bc-48d5-9a07-dc8e2f270063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Registration.htm?reg=1</value>
      <webElementGuid>1a414bdd-d549-45ea-a929-86127f04e2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uložit</value>
      <webElementGuid>d5e6cfbc-f37b-45cc-97d4-a268b5103877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderpage&quot;)/div[@class=&quot;order3&quot;]/div[@class=&quot;obuttons inner&quot;]/a[@class=&quot;btnx normal green arrowedRight floatRight order4&quot;]</value>
      <webElementGuid>8630dcfb-8c35-48fa-86d3-4fc7da856c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderpage']/div/div[2]/a</value>
      <webElementGuid>66471d6b-e849-4c97-88fd-547a3b383e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Více informací'])[1]/following::a[1]</value>
      <webElementGuid>35a6bec9-2c4a-4bfb-a045-dc888727aae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Právní základ zpracování'])[1]/following::a[2]</value>
      <webElementGuid>4a505f86-353a-454f-b463-f292bb702732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nejspolehlivější internetový obchod v ČR'])[1]/preceding::a[1]</value>
      <webElementGuid>462e4dd8-de34-4187-8664-6b536a6a3478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Registration.htm?reg=1')]</value>
      <webElementGuid>97143398-4207-47be-b52b-184afb5f0010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/a</value>
      <webElementGuid>7af09a63-eb73-4fe6-8480-3d253d309d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Registration.htm?reg=1' and (text() = 'Uložit' or . = 'Uložit')]</value>
      <webElementGuid>964800b0-5bfc-498a-86c0-cbf92d8b18b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
