<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_prihlasovaci_email</name>
   <tag></tag>
   <elementGuidId>f84df609-ab7e-48bb-b567-12d189d692e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edth1EmailLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edth1EmailLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edth1EmailLogin</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1788bad2-936a-438f-8131-9a24a9db98ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>128d1951-fca3-4bc6-bdbc-3712feb3456b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edth1EmailLogin</value>
      <webElementGuid>5061815d-b97f-4434-a94f-ccd980438945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>c4ce84d2-0dbf-41e7-bb5f-166dd1b61cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-type</name>
      <type>Main</type>
      <value>email-cant-exists</value>
      <webElementGuid>14db98c1-1392-436c-8fbc-60653d47c4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>035b40e4-e23f-47e9-a633-9f7871c42cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alzaformationtype</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>09c148a0-7bff-4f54-a700-e1461cbeb0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06d52908-61d5-4766-bf77-c5ffab6885ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edth1EmailLogin&quot;)</value>
      <webElementGuid>a354a8ac-6d4c-418c-a597-75a371d5cfca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edth1EmailLogin']</value>
      <webElementGuid>0065f03c-54d6-44c4-b678-616cabe3b1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel1']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>9313605c-663b-4dce-8427-5c3f5f1c83ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>0e1d14d7-7aaa-47db-bd2d-6872713e0299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'edth1EmailLogin' and @type = 'text']</value>
      <webElementGuid>2f24edd2-19bc-4d29-9a33-226015d02172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
