<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_potvrzeni_hesla</name>
   <tag></tag>
   <elementGuidId>bbc16e29-7762-4839-87e7-04ced9bfa8d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edth1PasswordConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edth1PasswordConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edth1PasswordConfirm</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f4d0b96-d6f4-4bdb-ab53-8be928be071c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox empt error</value>
      <webElementGuid>936c5edb-26d9-4592-8cf4-65111f34b839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edth1PasswordConfirm</value>
      <webElementGuid>5473fd0f-040d-4a57-8a45-5b2c58265334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-same-value-as</name>
      <type>Main</type>
      <value>edth1Password</value>
      <webElementGuid>b5e97f99-7ed7-4864-819b-c2da978a7140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fe1e2b3b-f804-42a5-880f-08576fb39f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4275813d-d1f0-4f6b-a32b-0503aced20ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edth1PasswordConfirm&quot;)</value>
      <webElementGuid>f2512c50-60ec-4ade-ac4b-a8176b73b672</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edth1PasswordConfirm']</value>
      <webElementGuid>13485d3c-9b63-49a2-905c-d0f6437fd83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='blockpsw2']/td[2]/input</value>
      <webElementGuid>2847f7c4-bf88-448f-ac0c-2bade90aa791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>9c11c9eb-1491-424e-87e7-e4a6a6737c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'edth1PasswordConfirm' and @type = 'password']</value>
      <webElementGuid>c3461347-df0f-47aa-af9a-6b0b74a0ba70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
