<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefon</name>
   <tag></tag>
   <elementGuidId>7e0a0a09-6c34-4afc-a391-db358f2aaeda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_cpcm_cpc_ud2_phoneCountryBasicPhoneValidator_inpTelNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_cpcm_cpc_ud2_phoneCountryBasicPhoneValidator_inpTelNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_ctl00_cpcm_cpc_ud2_phoneCountryBasicPhoneValidator_inpTelNumber</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e3c83d9-8d84-4485-bba4-28abf200b675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox inpTelNumber</value>
      <webElementGuid>2766ed73-3d3e-44de-9c75-f06b3b08fec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_cpcm_cpc_ud2_phoneCountryBasicPhoneValidator_inpTelNumber</value>
      <webElementGuid>4f725352-605d-4ee3-a45d-b5dded9f9c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>a11ae4c6-29b3-4174-a660-a5b35a49409a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-message-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>296d95b7-4a88-4501-9cab-cae7cecd5e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e07fd22e-9342-41b1-afc0-98c79eb6d521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-regex</name>
      <type>Main</type>
      <value>^(?:(?:\+|00)420)?((2[0-9]{8})|((31|32|35|37|38|39|41|47|46|48|49|51|53|54|55|56|57|58|59|70|72|73|77)[0-9]{7})|((60[1-8]|790|792|910|950|972|973|974)[0-9]{6})|((9555|9567)[0-9]{5})){1}$</value>
      <webElementGuid>2b20af02-b47b-4e04-95c0-9b79547b8510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-regex-message</name>
      <type>Main</type>
      <value>Číslo si prosím zkontrolujte. Pokud bude zadáno špatně, dopravce se vám nedovolá a doručení bude problematické.</value>
      <webElementGuid>08106ba1-e99f-414a-80f1-270e14a04ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-onblur</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85bc1c65-0870-4d86-93bf-1bfc8229d1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alzaformationtype</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>12d5cbfa-4de4-44d5-903b-15fdd898a764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36604942-9db5-4ab1-a722-da168fbe84ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selectedprefix</name>
      <type>Main</type>
      <value>+420</value>
      <webElementGuid>8bd3f2eb-316f-45af-8dde-b6d2a36dab86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_cpcm_cpc_ud2_phoneCountryBasicPhoneValidator_inpTelNumber&quot;)</value>
      <webElementGuid>0f22abe7-5463-4408-b891-9e5e4a201e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_cpcm_cpc_ud2_phoneCountryBasicPhoneValidator_inpTelNumber']</value>
      <webElementGuid>4ca5cfff-b3a5-4ecb-b8aa-248257a920b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_cpcm_cpc_ud2_phoneCountryBasicPhoneValidator_blockPhoneCountryValidator']/input</value>
      <webElementGuid>f1a750b7-5cf1-419e-9ba9-928f2d888262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>7b2c7aa1-719b-4748-9f8b-c8b792588879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ctl00_cpcm_cpc_ud2_phoneCountryBasicPhoneValidator_inpTelNumber' and @type = 'text']</value>
      <webElementGuid>c754b9eb-6f03-4756-9439-b7e373d0f102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
