<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>d07a0316-4b63-43b7-8225-d461c791ebd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edth1Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edth1Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edth1Password</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fc3a8ab-8b94-4a42-849f-3d2f3e2b69dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox forceKeyUpEvent passwordStrong</value>
      <webElementGuid>ac99ed77-18b6-467d-adde-5e18e1ac0d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edth1Password</value>
      <webElementGuid>48dff696-939a-4e10-8736-c3f1c46ad8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6d89d257-a38c-4cb3-8c24-7a5668c5080c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6207b89f-490f-4b6a-8da0-0532b7656010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation-forbidden-characters</name>
      <type>Main</type>
      <value>&lt;>()'&quot;%;&amp;</value>
      <webElementGuid>2550ab9c-068d-46ca-ab63-b9947996d032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dcbf7e87-ae09-4507-a22c-d6171494bcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edth1Password&quot;)</value>
      <webElementGuid>11427409-1b7e-4a9f-a152-7c747035cb45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edth1Password']</value>
      <webElementGuid>9b2246c4-3df6-4119-b9e8-c15b72a4ccf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='blockpsw']/td[2]/input</value>
      <webElementGuid>56e785e3-4c9c-4d3a-96b3-39fe4dc6c679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>fdbc2c27-0649-4d3e-af5e-6973b4128b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'edth1Password' and @type = 'password']</value>
      <webElementGuid>88d52f42-a762-4def-8228-9ca6134847d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
