<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_nova_registrace</name>
   <tag></tag>
   <elementGuidId>a82be6e6-0876-46f8-ace2-270a2b0e937b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='registerLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Nová registrace&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be512f2e-53ff-4202-b0c7-35f2f07a8cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerLink</value>
      <webElementGuid>5d134e5b-0863-461b-9e68-8593123663ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>registration-link</value>
      <webElementGuid>54c5de9a-88d8-44da-bd52-3dc552baff0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>5c2add2f-0984-452e-9f64-8b9e187ef48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.alza.cz/Registration.htm</value>
      <webElementGuid>4e6d62fd-2683-42db-92b1-f4a8d3504cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nová registrace</value>
      <webElementGuid>28bf871d-4703-4eae-8c5d-975aa0307cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerLink&quot;)</value>
      <webElementGuid>d5c73946-1fc3-4062-821e-57e8220bd253</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='registerLink']</value>
      <webElementGuid>5ef67210-45e2-45da-bbbc-8b366dbbd11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nová registrace')]</value>
      <webElementGuid>d9fbffa3-c9c9-4f5a-9b54-c364c41a5a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Přihlásit přes'])[1]/following::a[5]</value>
      <webElementGuid>72a69f02-c999-4c47-8cf9-254acf145a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Přihlásit se'])[1]/following::a[5]</value>
      <webElementGuid>021a0e04-416c-420e-8b1d-0cb0974f5549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 1994 - 2025 Alza.cz a.s.'])[1]/preceding::a[1]</value>
      <webElementGuid>78de2b25-3b73-4378-ab4c-9131de4336e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nová registrace']/parent::*</value>
      <webElementGuid>5cce8179-b2c2-413b-8b16-ae15f1afd896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.alza.cz/Registration.htm')]</value>
      <webElementGuid>3f7535ea-3630-426e-9ab4-2992518c5f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/a</value>
      <webElementGuid>ce067710-45ae-4fd7-abdf-c161fe54602b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'registerLink' and @href = 'https://www.alza.cz/Registration.htm' and (text() = 'Nová registrace' or . = 'Nová registrace')]</value>
      <webElementGuid>320fc83e-14e2-4f3b-9e3a-3ee296a2b33a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
