<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Samsung Galaxy S24</name>
   <tag></tag>
   <elementGuidId>e81f96bc-3525-479a-a588-40316c54b8a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='h1c']/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>h1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>63d253f4-86dc-47f8-bd7e-87bdbd85d9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samsung Galaxy S24</value>
      <webElementGuid>e82bbf74-269f-4015-b91e-cb5994c68b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1c&quot;)/h1[1]</value>
      <webElementGuid>6db848e4-daea-4506-a793-5a0bab5ad8c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='h1c']/h1</value>
      <webElementGuid>a89c3726-2427-4b94-b280-d4d528c8cd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samsung Galaxy S24'])[1]/following::h1[1]</value>
      <webElementGuid>d68ecd07-0d5d-4195-a883-4f7155d4e674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobilní telefony Samsung'])[1]/following::h1[1]</value>
      <webElementGuid>dcc4c6f8-af8d-4dbf-b04e-5eccf87fa87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zrušit vybrané parametry'])[2]/preceding::h1[1]</value>
      <webElementGuid>db210a73-fbdd-4fd6-a137-fac0334911b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokračovat'])[1]/preceding::h1[1]</value>
      <webElementGuid>b1944fa5-e395-4c1e-bfa4-a00fe6e07ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>be7faff9-a2bb-41e5-98f3-38a1b4624c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Samsung Galaxy S24' or . = 'Samsung Galaxy S24')]</value>
      <webElementGuid>549d9e41-b4ca-4b84-9c19-93ebe3164bf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
