<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search field</name>
   <tag></tag>
   <elementGuidId>4daf9c21-bc79-47f2-a392-227d7bb9f402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='exps']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;exps&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Co hledáte? Např. kabel AlzaPower...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d6077f4-49f5-4542-8e87-f43ba5fcc5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-alz-127 default-placeholder</value>
      <webElementGuid>882d7713-9167-475e-b061-8b578fa85985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Co hledáte? Např. kabel AlzaPower...</value>
      <webElementGuid>6cff299b-b3b4-4b92-bcad-14f2ba199b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a391282b-531b-4cf7-9f8a-8c870d9b3ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3d72fb9a-dcb7-444a-a75f-28653bcc84d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>:Rcliq:</value>
      <webElementGuid>f8ce3059-5ad7-4739-a2d4-02ed96ad1c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>334d91df-d960-40ec-8b3a-bec8934c3de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>cb48a887-e1bc-4f9f-bc3a-fe69ac1d0eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c846007f-abb4-4ad9-b669-c1e846ce0543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>searchInput</value>
      <webElementGuid>11f12f60-6489-442e-9b75-0568148f25d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>09edd3d6-fc0e-4faf-a219-7c31f8a5d4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exps</value>
      <webElementGuid>bd75178e-1869-4463-9f74-853ceab005e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;component header&quot;]/div[@class=&quot;MuiScopedCssBaseline-root header-1ym4w4j&quot;]/div[@class=&quot;header-alz-1&quot;]/div[@class=&quot;header-alz-3&quot;]/header[@class=&quot;header-alz-4 header-alz-6 header-alz-12&quot;]/div[@class=&quot;header-alz-10&quot;]/div[@class=&quot;header-alz-109 header-alz-118 showBackdrop&quot;]/div[@class=&quot;header-alz-119&quot;]/div[@class=&quot;header-alz-123 header-alz-120 default-placeholder&quot;]/input[@class=&quot;header-alz-127 default-placeholder&quot;]</value>
      <webElementGuid>91926a25-6a46-40a4-b939-bc4c888bf22c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='exps']</value>
      <webElementGuid>f9d5b34f-8ec9-4364-8fb4-fcac88553f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[2]/div/div/div/div/header/div[7]/div/div/div/input</value>
      <webElementGuid>0d77925c-094d-4be7-ad97-a65159f27855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>2f3e4da9-e73e-4b01-b97d-ea49b8c9e8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Co hledáte? Např. kabel AlzaPower...' and @type = 'text' and @name = 'exps']</value>
      <webElementGuid>b2b80481-61a6-480e-b93c-8b325e97fb55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
