<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_prihlasit</name>
   <tag></tag>
   <elementGuidId>baefaeaa-bd32-4c70-86bf-1a56ced37ba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.header-alz-31</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/div[2]/div/div/div/div/header/div/div/button/div[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;headerContextMenuToggleLogin&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4678cd61-da49-4f35-a534-77a51c1a35b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-alz-31</value>
      <webElementGuid>b47fe029-5cd6-498a-9ac0-8dbb1ebff1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64a7404e-9371-4831-af06-52c119a18f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20ff02c3-e76e-4e00-aac7-4b964479eeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Přihlásit se</value>
      <webElementGuid>eba89817-225f-4f02-8135-c08597a34f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>headerContextMenuToggleLogin</value>
      <webElementGuid>703da6f7-74fd-49cf-9ec7-f0d9b98c5e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Přihlásit se</value>
      <webElementGuid>d41736a6-e809-455c-ad9f-3494c530896f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;component header&quot;]/div[@class=&quot;MuiScopedCssBaseline-root header-1ym4w4j&quot;]/div[@class=&quot;header-alz-1&quot;]/div[@class=&quot;header-alz-3&quot;]/header[@class=&quot;header-alz-4&quot;]/div[@class=&quot;header-alz-15&quot;]/div[@class=&quot;header-alz-24&quot;]/button[@class=&quot;header-alz-25&quot;]/div[@class=&quot;header-alz-27 header-alz-40&quot;]/span[@class=&quot;header-alz-31&quot;]</value>
      <webElementGuid>373e847e-14de-4507-8c4f-3f6318c7cd98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[2]/div/div/div/div/header/div/div/button/div[2]/span[2]</value>
      <webElementGuid>2fad625e-27bc-4b39-9328-7aadb008be1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moje Alza'])[1]/following::span[1]</value>
      <webElementGuid>bb4dd130-9779-43fd-8833-aaa6f98d2829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hledat'])[1]/preceding::span[4]</value>
      <webElementGuid>db4b2df4-6383-4d34-922a-56cb1bb584b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alza'])[1]/preceding::span[5]</value>
      <webElementGuid>eae30d06-f415-4e90-b021-618ca0671114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Přihlásit se']/parent::*</value>
      <webElementGuid>864150ba-94c2-4b4d-bb41-960b8f6fa60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>eef96a8e-d8bc-449f-9fb4-9467b1d9263d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Přihlásit se' and (text() = 'Přihlásit se' or . = 'Přihlásit se')]</value>
      <webElementGuid>9a1e2de7-224c-47b4-a397-b9dec1d1fa80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
