<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cookie_accept</name>
   <tag></tag>
   <elementGuidId>a1668a92-4234-4614-abbe-1bfd21f192b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btnx.cookies-info__button.js-cookies-info-accept.cookies-info__button--white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='rootHtml']/body/div[8]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Rozumím&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5070b489-d35a-46cf-9d59-89f759421aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnx cookies-info__button js-cookies-info-accept cookies-info__button--white</value>
      <webElementGuid>724c8cb1-ab5f-400a-9293-01c35f24894d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-api-url</name>
      <type>Main</type>
      <value>https://webapi.alza.cz/api/anonymous/v2/activities?vst=18011862-262d-4c84-b290-47401bf5d2f2</value>
      <webElementGuid>cb4b2f96-3650-4a3b-b05f-8d94ecf27a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-type-value</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>6532d5f2-584b-471f-bcc4-4794b1fc0307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-id-value</name>
      <type>Main</type>
      <value>1023</value>
      <webElementGuid>f7ffab87-d057-48ea-883b-f3b202ed2165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-speed-curve</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>01ad7403-0c1e-4883-854b-a1c5586a5f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:Alza.Web.Cookies.acceptAllCookies();</value>
      <webElementGuid>c3784103-f5d4-4dac-b3fd-62c9051ca5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rozumím</value>
      <webElementGuid>ca454914-de56-484f-83f5-8e7687f2c36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootHtml&quot;)/body[@class=&quot;default alza-cz alza new-header--small-sticky&quot;]/div[@class=&quot;js-cookies-info cookies-info&quot;]/div[@class=&quot;cookies-info__container&quot;]/div[@class=&quot;cookies-info__inner&quot;]/div[@class=&quot;cookies-info__buttons&quot;]/a[@class=&quot;btnx cookies-info__button js-cookies-info-accept cookies-info__button--white&quot;]</value>
      <webElementGuid>4a7c3bb3-247f-47c3-98ff-3db465eacb38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='rootHtml']/body/div[8]/div/div/div[2]/a</value>
      <webElementGuid>f460a72d-23c0-4aad-a0e4-d56ef877bcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rozumím')]</value>
      <webElementGuid>740e3b4d-c718-473f-8867-0d3513504409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podmínkách ochrany os. údajů'])[1]/following::a[1]</value>
      <webElementGuid>4d4cc704-595b-495b-ba46-f28b9218d0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Více o Vašich právech'])[1]/following::a[2]</value>
      <webElementGuid>6ea31371-82cb-4e23-aa78-13de9e36a8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podrobné nastavení'])[1]/preceding::a[1]</value>
      <webElementGuid>4b9b51f0-2a61-4e2f-9785-c1d42c7d983a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odmítnout vše'])[1]/preceding::a[2]</value>
      <webElementGuid>873434df-0f43-4e90-beb1-6c28f38d9a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rozumím']/parent::*</value>
      <webElementGuid>8fb839df-db2b-4897-8321-8751ade815f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:Alza.Web.Cookies.acceptAllCookies();')]</value>
      <webElementGuid>4d634b3a-cb19-44b3-ac23-9522a70bb135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/a</value>
      <webElementGuid>04701af7-a63b-4ce5-b161-69c64e32241b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:Alza.Web.Cookies.acceptAllCookies();' and (text() = 'Rozumím' or . = 'Rozumím')]</value>
      <webElementGuid>2f57fa00-4e32-481b-9b6b-0ce879178f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
